#!/usr/bin/env bash
# install-hooks.sh — Install git hooks in ~/.claude/skills-repo/.git/hooks/
# that auto-run sync-to-cache.sh on commits, merges, and branch checkouts.
#
# Run this ONCE to set up automation. After that, every:
#   - git commit      (on this machine)  → triggers post-commit  → sync
#   - git pull        (on this machine)  → triggers post-merge   → sync
#   - git checkout    (branch switch)    → triggers post-checkout → sync
# automatically refreshes the plugin cache.
#
# Hooks live in .git/hooks/ which is NOT tracked by git — they're local to
# this machine. If you set up a new machine, re-run this script there.
#
# To uninstall: delete ~/.claude/skills-repo/.git/hooks/post-commit,
# post-merge, and post-checkout.

set -euo pipefail

REPO_ROOT="$HOME/.claude/skills-repo"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
SYNC_SCRIPT="$REPO_ROOT/protocol-kri-extractor/scripts/sync-to-cache.sh"

if [ ! -d "$REPO_ROOT/.git" ]; then
    echo "✗ install-hooks: $REPO_ROOT is not a git repo" >&2
    exit 1
fi

if [ ! -f "$SYNC_SCRIPT" ]; then
    echo "✗ install-hooks: sync script not found: $SYNC_SCRIPT" >&2
    exit 1
fi

chmod +x "$SYNC_SCRIPT"

install_hook() {
    local event="$1"
    local path="$HOOKS_DIR/$event"
    cat > "$path" <<EOF
#!/usr/bin/env bash
# Auto-generated by install-hooks.sh — do not edit.
# Syncs protocol-kri-extractor to the plugin cache after every $event.
# Never blocks a git operation: sync errors are logged but exit 0.
"$SYNC_SCRIPT" || true
EOF
    chmod +x "$path"
    echo "  ✓ installed $event"
}

install_hook post-commit
install_hook post-merge
install_hook post-checkout

echo
echo "Done. From now on, every commit / pull / checkout on this machine will"
echo "auto-sync the protocol-kri-extractor skill to the plugin cache."
echo
echo "To sync manually: $SYNC_SCRIPT"
echo "To uninstall:     rm $HOOKS_DIR/post-commit $HOOKS_DIR/post-merge $HOOKS_DIR/post-checkout"
